// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeymsdwtbrpzhvxxekjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFleW1zZHd0YnJwemh2eHhla2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDAxODIsImV4cCI6MjA2NDIxNjE4Mn0.rI7ExA-aOnlf_HqpL3_iGtZsb9oLO0AxUkqCrbntsWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);